### ISSUE TITLE
Matlab version?

### ISSUE THREAD

**Issue by dezorkic** [cyrilwsh/DAFX_ADRESS_byJuce#1]
Hi,

nice work on this one! I saw your report pdf and it mentioned a version in Matlab.
Is it possible for you to share that version as well?

Thank you very much!

**Comment by cyrilwsh** [comment]
Hi,

I've uploaded the original matlab code already.
However I'm not sure are they all good since I don't have matlab at hand now.
If you have any questions or ideas please feel free to tell me.
Cheers.

**Comment by dezorkic** [comment]
Thank you very much!
